# fly.toml (النسخة الصحيحة والمعدّلة للعامل)

# سيتم استبدال اسم التطبيق تلقائياً بواسطة سكربت المنسق
app = "worker-placeholder"
primary_region = "sin"

# هذا هو القسم الأهم.
# نحن نحدد هنا الأمر الذي سيتم تشغيله عند بدء تشغيل الآلة.
[processes]
  # اسم العملية هو "app"، والأمر هو تشغيل ملف البايثون الخاص بنا.
  # علامات الاقتباس المفردة ضرورية لأن اسم الملف يحتوي على مسافات.
  app = "python 'main.py'"

# تحديد حجم ومواصفات الآلة الافتراضية
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
